if(EXISTS ${CMAKE_SOURCE_DIR}/installed)
    set(LIBGIT2_INCLUDE ${CMAKE_SOURCE_DIR}/installed/include)
    if (WIN32)
        set(LIBGIT2_LIBRARY ${CMAKE_SOURCE_DIR}/installed/lib/git2.lib)
    else()
        set(LIBGIT2_LIBRARY ${CMAKE_SOURCE_DIR}/installed/lib/libgit2.so)
    endif()
    message("-- libgit2 found")
elseif()
    message(FATAL_ERROR "-- libgit2 not found")
endif()
